spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
  datasource:
    url: jdbc:h2:mem:testdb;NON_KEYWORDS=USER
    username: filip
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true
  h2:
    console:
      enabled: true
  security:
    user:
      name: filip
      password: 123456
  data:
    jpa:
      repositories:
        bootstrap-mode: default
